fixing scaffold typo

diff --git a/bin/flask-diamond b/bin/flask-diamond
--- a/bin/flask-diamond
+++ b/bin/flask-diamond
@@ -1,15 +1,36 @@
 #!/bin/bash
 # Flask-Diamond (c) Ian Dennis Miller
 
+define(){ IFS='\n' read -r -d '' ${1} || true; }
+
+define USAGE <<'EOF'
+usage: flask-diamond [scaffold_type] [target_path]
+
+example: flask-diamond app ~/my-new-project
+
+See http://flask-diamond.org for more information.
+EOF
+
+VERSION=$(python -c 'import flask_diamond.__meta__; print("Flask-Diamond {0}".format(flask_diamond.__meta__.__version__))')
+echo $VERSION
+echo
+
 if [ -z "$1" ]; then
-    echo "error: expected a scaffold type: [app, model, views]"
-    echo "usage: flask-diamond app ~/my-new-project"
+    echo "ERROR: expected a scaffold type {app, example-models, example-views}"
+    echo
+    echo "Try 'flask-diamond help' for more information."
+    exit
+fi
+
+if [ "$1" == "help" ]; then
+    echo "$USAGE"
     exit
 fi
 
 if [ -z "$2" ]; then
-    echo "error: expected a target directory"
-    echo "usage: flask-diamond app ~/my-new-project"
+    echo "ERROR: expected a target directory"
+    echo
+    echo "Try 'flask-diamond help' for more information."
     exit
 fi
 
@@ -28,26 +49,35 @@ if [ "$1" == "app" ]; then
 
     echo "Cleaning up..."
     rm /tmp/mrbob.ini
+    exit
 fi
 
-if [ "$1" == "model" ]; then
+if [ "$1" == "example-models" ]; then
     echo "Scaffold a Flask-Diamond model"
 
     if [ -f $2/.mrbob.ini ]; then
-        mrbob -w --config "$2/.mrbob.ini" -O "$2" $VIRTUAL_ENV/share/skels/example-model
+        mrbob -w --config "$2/.mrbob.ini" -O "$2" $VIRTUAL_ENV/share/skels/example-models
     else
         echo "ERROR: $2/.mrbob.ini does not exist."
+        echo
         echo "This must be run in the root directory of a Flask-Diamond application."
     fi
+    exit
 fi
 
-if [ "$1" == "views" ]; then
+if [ "$1" == "example-views" ]; then
     echo "Scaffold the default Flask-Diamond views"
 
     if [ -f $2/.mrbob.ini ]; then
         mrbob -w --config "$2/.mrbob.ini" -O "$2" $VIRTUAL_ENV/share/skels/example-views
     else
         echo "ERROR: $2/.mrbob.ini does not exist."
+        echo
         echo "This must be run in the root directory of a Flask-Diamond application."
     fi
+    exit
 fi
+
+echo "ERROR: expected a scaffold type {app, example-models, example-views}"
+echo
+echo "Try 'flask-diamond help' for more information."
